---
title: "NN January Tournament"
author: "by NN Sheep"
output: 
  flexdashboard::flex_dashboard:
    theme: 
      version: 4
      bootswatch: pulse
    vertical_layout: fill
---

```{r setup, include=FALSE, message=FALSE}
knitr::opts_chunk$set(echo = FALSE, 
                      message = FALSE, 
                      warning = FALSE)
library(tidyverse)
library(knitr)
library(flexdashboard)
library(RColorBrewer)

# load in data
raw <- readxl::read_excel('nn_jan.xlsx') 
```

```{r}
#### INITIALISATIONS ####

# plot template
theme_blank <- function(){
  theme(axis.title = element_blank(),
        axis.ticks = element_blank(),
        axis.text.x = element_blank(),
        panel.background = element_blank(),
        panel.grid = element_blank())}

# colour palette for conistency
#pal <- c('#800000','#767676','#FFA319','#8A9045','#155F83','#C16622')
pal <- colorRampPalette(brewer.pal(6, "Purples"))

# scoring system
a<-c(25,22,19,17,16,15,14,13,12,11,10,9,8,7,6,5,4,3,2,1)
b<-rev(1:20)

# function to create df for each day (might be a better solution)
tmp_df <- function(x,d){
  return(filter(x,Day==d) %>% 
           mutate(Team=fct_reorder(Team,-Rank)) %>%
           arrange(Rank))
}

h2h_df <- function(x,d){
  pivot_wider(x, id_cols=h2h, names_from=Result, values_from=Team) %>% 
    select(-h2h) 
}

indiv_df <- function(x,d){
  filter(x,Day==d & !is.na(Time)) %>%
  select(Rank,Player,Time) %>% 
  mutate(Player=fct_reorder(Player,-Rank))
}
```

``` {r}
#### DATA PREP ####
# gather columns of same type of info and add column for day
results <- pivot_longer(raw,-c(1:2), values_transform = as.character) %>%
  # collate cols into one day col and one time col
  separate(name,c('Data','Day'),'_') %>% 
  pivot_wider(names_from = Data, values_from = value) %>%
  mutate(Time=round(as.numeric(Time),2), Day=as.numeric(Day)) %>%
  # sort by lowest time for each day and add a rank column
  arrange(Day,Time) %>%
  mutate(Rank=rep(1:n_distinct(Player),n_distinct(Day)),.before=Player) %>%
  mutate(rev_pts=rev(Rank),
         dw_pts=rep(a[1:n_distinct(Player)],n_distinct(Day)))
```

# Day 1
##### **Car: `r raw$Car_1[1]`**
##### **Track: `r raw$Track_1[1]`**


Column 
--------------
### Time 
```{r}
tmp<-indiv_df(results,1)
# plot team performance
ggplot(tmp, aes(Time,Player,fill=Player)) +
  geom_col(position = 'dodge', show.legend=FALSE) +
  scale_fill_manual(values = pal(nrow(tmp))) +
  coord_cartesian(xlim=c(min(tmp$Time)*.999,max(tmp$Time)**1.002)) +
  theme_blank() + 
  annotate('text', x=rev(tmp$Time)+.04, y=1:length(tmp$Time), 
           label=paste0(format(rev(tmp$Time),nsmall=2),'s'))
```

Column 
--------------
### Leaderboard 
```{r}
# Table of overall player rankings
kable(tmp)
```

# Day 2
##### Car: `r raw$Car_2[1]`
##### Track: `r raw$Track_2[1]`


Column 
--------------
### Time 
```{r}
tmp<-indiv_df(results,2)
# plot team performance
ggplot(tmp, aes(Time,Player,fill=Player)) +
  geom_col(position = 'dodge', show.legend=FALSE) +
  scale_fill_manual(values = pal(nrow(tmp))) +
  coord_cartesian(xlim=c(min(tmp$Time)*.999,max(tmp$Time)**1.002)) +
  theme_blank() + 
  annotate('text', x=rev(tmp$Time)+.04, y=1:length(tmp$Time), 
           label=paste0(format(rev(tmp$Time),nsmall=2),'s'))
```

Column 
--------------
### Leaderboard 
```{r}
# Table of overall player rankings
kable(tmp)
```

# Day 3

##### Car: `r raw$Car_3[1]`
##### Track: `r raw$Track_3[1]`


Column 
--------------
### Time 
```{r}
tmp<-indiv_df(results,3)
# plot team performance
ggplot(tmp, aes(Time,Player,fill=Player)) +
  geom_col(position = 'dodge', show.legend=FALSE) +
  scale_fill_manual(values = pal(nrow(tmp))) +
  coord_cartesian(xlim=c(min(tmp$Time)*.999,max(tmp$Time)**1.002)) +
  theme_blank() + 
  annotate('text', x=rev(tmp$Time)+.04, y=1:length(tmp$Time), 
           label=paste0(format(rev(tmp$Time),nsmall=2),'s'))
```

Column 
--------------
### Leaderboard 
```{r}
# Table of overall player rankings
kable(tmp)
```

# Final Standings 

Column 
--------------
### Average Time 
```{r}
tmp <- results %>%
    select(Player,Time,Day,rev_pts,dw_pts) %>% 
    group_by(Player) %>%
    summarise(Time = sum(Time)/3,
              `DW Points`=sum(dw_pts),
              `Reverse Points`=sum(rev_pts)) %>%
    arrange(Time) %>%
    mutate(Rank = 1:nrow(.),.before = Player,
           Player=fct_reorder(Player,-Rank))

# plot performance
ggplot(tmp, aes(Time,Player,fill=Player)) +
  geom_col(position = 'dodge', show.legend=FALSE) +
  scale_fill_manual(values = pal(nrow(tmp))) +
  coord_cartesian(xlim=c(min(tmp$Time)*.999,max(tmp$Time)**1.002)) +
  theme_blank() + 
  annotate('text', x=rev(tmp$Time)+.04, y=1:length(tmp$Time), 
           label=paste0(format(rev(tmp$Time),nsmall=2),'s'))
```

Column 
--------------
### Final Standings: DW Scoring
```{r}
# Table of overall player rankings
kable(tmp %>%
        select(Player, `DW Points`) %>%
        arrange(desc(`DW Points`)) %>%
        mutate(Rank = 1:nrow(tmp),.before=1)
        )
```

Column 
--------------
### Final Standings: Reverse Scoring
```{r}
# Table of overall player rankings
kable(tmp %>%
        select(Player, `Reverse Points`) %>%
        arrange(desc(`Reverse Points`)) %>%
        mutate(Rank = 1:nrow(tmp),.before=1)
        )
```



